# Generated by Django 4.0 on 2022-04-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_newsletterrecipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterrecipients',
            name='name',
        ),
    ]
