# Generated by Django 4.0 on 2022-04-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_newsletterrecipients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipients',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
